# POST http://localhost:3000/api/v1/user/login HTTP/1.1
# Content-Type: application/json

# {
#   "account": "18026086011",
#   "password": "123456"
# }

# POST http://localhost:3000/api/v1/room/add HTTP/1.1
# Content-Type: application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6OSwiY3JlYXRlX3RpbWUiOiIyMDI0LTA5LTI2VDA2OjUwOjA1LjAwMFoiLCJhY2NvdW50IjoiMTgwMjYwODYwMTEiLCJwYXNzd29yZCI6IjEyMzQ1NiIsImlhdCI6MTcyNzMzNTA2MiwiZXhwIjoxNzI3OTM5ODYyfQ.HRHK3VM9eZJqaDklPuBoSsKahP-a74U0pp3zxYE6Bt8

# {
#   "room_name": "房间名一",
#   "room_pwd": "12445678",
#   "user_id": 9
# }

GET http://localhost:3000/api/v1/room/get?page=1&pageSize=10 HTTP/1.1
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6OSwiY3JlYXRlX3RpbWUiOiIyMDI0LTA5LTI2VDA2OjUwOjA1LjAwMFoiLCJhY2NvdW50IjoiMTgwMjYwODYwMTEiLCJwYXNzd29yZCI6IjEyMzQ1NiIsImlhdCI6MTcyNzMzNTA2MiwiZXhwIjoxNzI3OTM5ODYyfQ.HRHK3VM9eZJqaDklPuBoSsKahP-a74U0pp3zxYE6Bt8


# DELETE  http://localhost:3000/api/v1/room/del/1 HTTP/1.1
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6OSwiY3JlYXRlX3RpbWUiOiIyMDI0LTA5LTI2VDA2OjUwOjA1LjAwMFoiLCJhY2NvdW50IjoiMTgwMjYwODYwMTEiLCJwYXNzd29yZCI6IjEyMzQ1NiIsImlhdCI6MTcyNzMzNTA2MiwiZXhwIjoxNzI3OTM5ODYyfQ.HRHK3VM9eZJqaDklPuBoSsKahP-a74U0pp3zxYE6Bt8
